// The stellar.toml of an organization (SEP-0001): the public file where it says who it is, so wallets and explorers can
// show a name and a logo instead of an address. Verifire only writes it; the company publishes it on its own domain at
// https://<domain>/.well-known/stellar.toml, over HTTPS and with `Access-Control-Allow-Origin: *`.
//
// Pure: it answers the file and what could not go in it, so the panel can say so instead of writing a broken file.

export interface TomlInput {
  commercialName: string;
  legalName: string;
  website: string;
  description: string;
  // The organization's own address, on the domain of `website` (ORG_OFFICIAL_EMAIL).
  officialEmail: string;
  supportEmail: string;
  // Public https address of the logo (ORG_LOGO).
  logoUrl: string;
}

export interface TomlResult {
  text: string;
  // The ORG_* keys written, and the ones left out because their data is missing or not valid for that key.
  included: string[];
  omitted: { key: string; reason: 'missing' | 'not-https' }[];
  // Things the file would carry that SEP-0001 asks to be otherwise.
  warnings: ('website-not-https' | 'email-other-domain')[];
}

// A TOML basic string: quotes, backslashes and control characters are written escaped, so no value can break the file
// or add a line of its own.
export const tomlString = (value: string) =>
  `"${value.replace(/[\\"\u0000-\u001f\u007f]/g, (char) => {
    if (char === '\\') return '\\\\';
    if (char === '"') return '\\"';
    if (char === '\n') return '\\n';
    if (char === '\r') return '\\r';
    if (char === '\t') return '\\t';
    return `\\u${char.charCodeAt(0).toString(16).padStart(4, '0')}`;
  })}"`;

const hostOf = (address: string) => {
  try {
    return new URL(address).hostname.toLowerCase();
  } catch {
    return '';
  }
};

const isHttps = (address: string) => /^https:\/\//i.test(address);

export const buildStellarToml = (input: TomlInput): TomlResult => {
  const trade = input.commercialName.trim();
  const legal = input.legalName.trim();
  const website = input.website.trim();
  const logo = input.logoUrl.trim();
  const official = input.officialEmail.trim();
  const support = input.supportEmail.trim();
  const description = input.description.trim();

  const lines: [string, string][] = [];
  const omitted: TomlResult['omitted'] = [];
  const add = (key: string, value: string, { https = false }: { https?: boolean } = {}) => {
    if (!value) omitted.push({ key, reason: 'missing' });
    else if (https && !isHttps(value)) omitted.push({ key, reason: 'not-https' });
    else lines.push([key, value]);
  };

  // ORG_NAME is the legal name; the trade name goes in ORG_DBA ("doing business as") when it is a different one.
  add('ORG_NAME', legal || trade);
  if (legal && trade && legal !== trade) add('ORG_DBA', trade);
  add('ORG_URL', website);
  add('ORG_LOGO', logo, { https: true });
  add('ORG_DESCRIPTION', description);
  add('ORG_OFFICIAL_EMAIL', official);
  if (support && support !== official) add('ORG_SUPPORT_EMAIL', support);

  const warnings: TomlResult['warnings'] = [];
  if (website && !isHttps(website)) warnings.push('website-not-https');
  const domain = hostOf(website);
  if (domain && official && !(official.split('@')[1] ?? '').toLowerCase().endsWith(domain.replace(/^www\./, ''))) {
    warnings.push('email-other-domain');
  }

  const text = [
    '# stellar.toml generated by Verifire (SEP-0001).',
    '# Publish it at https://<your-domain>/.well-known/stellar.toml, over HTTPS and with the header',
    '# Access-Control-Allow-Origin: *   The domain has to be the one of ORG_URL.',
    '',
    '[DOCUMENTATION]',
    ...lines.map(([key, value]) => `${key} = ${tomlString(value)}`),
    ''
  ].join('\n');

  return { text, included: lines.map(([key]) => key), omitted, warnings };
};
